"""initial migration with enums

Revision ID: 82f711fbd1bd
Revises: 
Create Date: 2025-10-13 15:39:39.208584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f711fbd1bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('specversion', sa.Enum('V1_0', name='specversion'), nullable=False),
    sa.Column('type', sa.Enum('WAREHOUSE_MOVEMENT', name='eventtype'), nullable=False),
    sa.Column('datacontenttype', sa.Enum('JSON', name='datacontenttype'), nullable=False),
    sa.Column('dataschema', sa.String(), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('arrival', 'departure', name='movementevent'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_index(op.f('ix_movements_movement_id'), 'movements', ['movement_id'], unique=False)
    op.create_index(op.f('ix_movements_product_id'), 'movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_movements_warehouse_id'), 'movements', ['warehouse_id'], unique=False)
    op.create_table('warehouse_states',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_states')
    op.drop_index(op.f('ix_movements_warehouse_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_product_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    # ### end Alembic commands ###
